In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
df = pd.read_csv("Train-1617360447408-1660719685476.csv")

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66587 entries, 0 to 66586
Data columns (total 49 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   index               66587 non-null  int64  
 1   encounter_id        66587 non-null  int64  
 2   patient_id          66587 non-null  int64  
 3   race                66587 non-null  object 
 4   gender              66587 non-null  object 
 5   age                 66587 non-null  object 
 6   weight              66587 non-null  object 
 7   time_in_hospital    66587 non-null  int64  
 8   medical_specialty   66587 non-null  object 
 9   num_lab_procedures  66587 non-null  int64  
 10  num_procedures      66587 non-null  int64  
 11  num_medications     66587 non-null  int64  
 12  number_outpatient   66587 non-null  int64  
 13  number_emergency    66587 non-null  int64  
 14  number_inpatient    66587 non-null  int64  
 15  diag_1              66587 non-null  object 
 16  diag

In [18]:
df.head()

index  encounter_id  patient_id             race  gender      age weight  \
0  69375     197029140    51521940         Hispanic    Male  [80-90)      ?   
1  57272     163571946    92631357        Caucasian    Male  [60-70)      ?   
2  82347     256497366    30023982        Caucasian  Female  [50-60)      ?   
3  89608     289891212    93606021  AfricanAmerican  Female  [70-80)      ?   
4  24091      81873900    23464296        Caucasian    Male  [70-80)      ?   

   time_in_hospital medical_specialty  num_lab_procedures  ...  X19   X20  \
0                 4  Emergency/Trauma                  39  ...   No    No   
1                 3  Emergency/Trauma                  34  ...   No    No   
2                 6        Nephrology                  50  ...   No  Down   
3                 5                 ?                  63  ...   No  Down   
4                 9        Psychiatry                  17  ...   No    No   

   X21  X22  X23 X24 X25 change diabetesMed  readmitted  
0   No   No   No  No  No     No         Yes           1  
1   No   No   No  No  No     No          No           0  
2   No   No   No  No  No     Ch         Yes           1  
3   No   No   No  No  No     Ch         Yes           1  
4   No   No   No  No  No     No          No           1  

[5 rows x 49 columns]

In [19]:
for c in list(df.columns):
    
    # get a list of unique values
    n = df[c].unique()
    
    # if number of unique values is less than 30, print the values. Otherwise print the number of unique values
    if len(n)<30:
        print(c)
        print(n)
    else:
        print(c + ': ' +str(len(n)) + ' unique values')

index: 48911 unique values
encounter_id: 48911 unique values
patient_id: 39650 unique values
race
['Hispanic' 'Caucasian' 'AfricanAmerican' '?' 'Other' 'Asian']
gender
['Male' 'Female' 'Unknown/Invalid']
age
['[80-90)' '[60-70)' '[50-60)' '[70-80)' '[40-50)' '[20-30)' '[30-40)'
 '[90-100)' '[0-10)' '[10-20)']
weight
['?' '[0-25)' '[75-100)' '[50-75)' '[25-50)' '[125-150)' '[150-175)'
 '[100-125)' '>200' '[175-200)']
time_in_hospital
[ 4  3  6  5  9 13  2  7  1 11 12 10 14  8]
medical_specialty: 65 unique values
num_lab_procedures: 113 unique values
num_procedures
[1 2 0 3 4 5 6]
num_medications: 71 unique values
number_outpatient: 33 unique values
number_emergency
[ 1  0  3  2  6  8  5  4 12  7 20 19  9 16 10 18 63 13 11 22 15 28 25 21
 24 46]
number_inpatient
[ 4  0  5  1  3  2  6  9  7 10  8 11 15 14 12 13 19 16 18]
diag_1: 652 unique values
diag_2: 656 unique values
diag_3: 707 unique values
diag_4: 707 unique values
diag_5: 48911 unique values
number_diagnoses
[ 9  6  7  5  4  2  8

In [20]:
df = df.replace('?',np.nan)

In [21]:
cols_num = ['time_in_hospital','num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient','number_diagnoses']

In [22]:
df[cols_num].isnull().sum()

time_in_hospital      0
num_lab_procedures    0
num_procedures        0
num_medications       0
number_outpatient     0
number_emergency      0
number_inpatient      0
number_diagnoses      0
dtype: int64

In [23]:
cols_cat = ['race', 'gender','medical_specialty','X1','X2','X3','X4','X5','X6','X7','X9','X8','X10','X11',
               'X12','X13','X14','X15','X16','X17','X18','X19','X20','X21','X22','X23','X24','X25','change', 'diabetesMed']

In [24]:
df[cols_cat].isnull().sum()

race                  1504
gender                   0
medical_specialty    32672
X1                       0
X2                       0
X3                       0
X4                       0
X5                       0
X6                       0
X7                       0
X9                       0
X8                       0
X10                      0
X11                      0
X12                      0
X13                      0
X14                      0
X15                      0
X16                      0
X17                      0
X18                      0
X19                      0
X20                      0
X21                      0
X22                      0
X23                      0
X24                      0
X25                      0
change                   0
diabetesMed              0
dtype: int64

In [25]:
df['race'] = df['race'].fillna('UNK')
df['medical_specialty'] = df['medical_specialty'].fillna('UNK')

In [26]:
print('Number medical specialty:', df.medical_specialty.nunique())
df.groupby('medical_specialty').size().sort_values(ascending = False)

Number medical specialty: 65


medical_specialty
UNK                               32672
InternalMedicine                   9460
Emergency/Trauma                   4986
Family/GeneralPractice             4924
Cardiology                         3434
                                  ...  
Speech                                2
Proctology                            1
Pediatrics-Hematology-Oncology        1
DCPTEAM                               1
Psychiatry-Addictive                  1
Length: 65, dtype: int64

In [27]:
top_10 = ['UNK','InternalMedicine','Emergency/Trauma',\
          'Family/GeneralPractice', 'Cardiology','Surgery-General' ,\
          'Nephrology','Orthopedics',\
          'Orthopedics-Reconstructive','Radiologist']


df['med_spec'] = df['medical_specialty'].copy()


df.loc[~df.med_spec.isin(top_10),'med_spec'] = 'Other'

In [28]:
df.groupby('med_spec').size()

med_spec
Cardiology                     3434
Emergency/Trauma               4986
Family/GeneralPractice         4924
InternalMedicine               9460
Nephrology                     1098
Orthopedics                     912
Orthopedics-Reconstructive      812
Other                          5455
Radiologist                     767
Surgery-General                2067
UNK                           32672
dtype: int64

In [30]:
df[['age', 'weight']].head()

age weight
0  [80-90)    NaN
1  [60-70)    NaN
2  [50-60)    NaN
3  [70-80)    NaN
4  [70-80)    NaN

In [31]:
df.groupby('age').size()

age
[0-10)        100
[10-20)       428
[20-30)      1154
[30-40)      2414
[40-50)      6324
[50-60)     11378
[60-70)     14845
[70-80)     17031
[80-90)     11080
[90-100)     1833
dtype: int64

In [34]:
age_id ={'[0-10)':100,
         '[10-20)' :428,
         '[20-30)' :1154,
         '[30-40)' :2414,
         '[40-50)' :6324,
         '[50-60)' :11378,
         '[60-70)' :14845,
         '[70-80)' :17031,
         '[80-90)' :11080,
         '[90-100)':1833}
df['age_group'] = df.age.replace(age_id)

In [35]:
df.weight.notnull().sum()

2133

In [36]:
df['has_weight'] = df.weight.notnull().astype('int')

In [37]:
cols_extra = ['age_group','has_weight']

In [40]:
print('Total number of features:', len(cols_num + cols_extra))
print('Numerical Features:',len(cols_num))
print('Extra features:',len(cols_extra))

Total number of features: 10
Numerical Features: 8
Extra features: 2


In [41]:
df[cols_num +  cols_extra].isnull().sum().sort_values(ascending = False).head(10)

time_in_hospital      0
num_lab_procedures    0
num_procedures        0
num_medications       0
number_outpatient     0
number_emergency      0
number_inpatient      0
number_diagnoses      0
age_group             0
has_weight            0
dtype: int64

In [43]:
col2use = cols_num + cols_extra
df_data = df[col2use + ['readmitted']]

In [44]:
df_data = df_data.sample(n = len(df_data), random_state = 42)
df_data = df_data.reset_index(drop = True)

In [45]:
df_valid_test=df_data.sample(frac=0.30,random_state=42)
print('Split size: %.3f'%(len(df_valid_test)/len(df_data)))

Split size: 0.300


In [46]:
df_test = df_valid_test.sample(frac = 0.5, random_state = 42)
df_valid = df_valid_test.drop(df_test.index)

In [47]:
df_train_all=df_data.drop(df_valid_test.index)

In [50]:
print('all samples (n = %d)'%len(df_data))
assert len(df_data) == (len(df_test)+len(df_valid)+len(df_train_all)),'math didnt work'

all samples (n = 66587)


In [53]:
rows_pos = df_train_all.readmitted == 1
df_train_pos = df_train_all.loc[rows_pos]
df_train_neg = df_train_all.loc[~rows_pos]

# merge the balanced data
df_train = pd.concat([df_train_pos, df_train_neg.sample(n = len(df_train_pos), random_state = 42)],axis = 0)

# shuffle the order of training samples 
df_train = df_train.sample(n = len(df_train), random_state = 42).reset_index(drop = True)

In [54]:
df_train_all.to_csv('df_train_all.csv',index=False)
df_train.to_csv('df_train.csv',index=False)
df_valid.to_csv('df_valid.csv',index=False)
df_test.to_csv('df_test.csv',index=False)

In [55]:
X_train = df_train[col2use].values
X_train_all = df_train_all[col2use].values
X_valid = df_valid[col2use].values

y_train = df_train['readmitted'].values
y_valid = df_valid['readmitted'].values

print('Training All shapes:',X_train_all.shape)
print('Training shapes:',X_train.shape, y_train.shape)
print('Validation shapes:',X_valid.shape, y_valid.shape)

Training All shapes: (46611, 10)
Training shapes: (43346, 10) (43346,)
Validation shapes: (9988, 10) (9988,)


In [56]:
from sklearn.preprocessing import StandardScaler

scaler  = StandardScaler()
scaler.fit(X_train_all)

StandardScaler()

In [57]:
import pickle
scalerfile = 'scaler.sav'
pickle.dump(scaler, open(scalerfile, 'wb'))

In [58]:
scaler = pickle.load(open(scalerfile, 'rb'))

In [59]:
X_train_tf = scaler.transform(X_train)
X_valid_tf = scaler.transform(X_valid)

In [64]:
from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score
def calc_specificity(y_actual, y_pred, thresh):
    # calculates specificity
    return sum((y_pred < thresh) & (y_actual == 0)) /sum(y_actual ==0)

def print_report(y_actual, y_pred, thresh):
    
    auc = roc_auc_score(y_actual, y_pred)
    accuracy = accuracy_score(y_actual, (y_pred > thresh))
    recall = recall_score(y_actual, (y_pred > thresh))
    precision = precision_score(y_actual, (y_pred > thresh))
    specificity = calc_specificity(y_actual, y_pred, thresh)
    print('AUC:%.3f'%auc)
    print('accuracy:%.3f'%accuracy)
    print('recall:%.3f'%recall)
    print('precision:%.3f'%precision)
    print('specificity:%.3f'%specificity)
    print(' ')
    return auc, accuracy, recall, precision, specificity 

In [65]:
thresh = 0.5

In [66]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors = 100)
knn.fit(X_train_tf, y_train)

KNeighborsClassifier(n_neighbors=100)

In [67]:
y_train_preds = knn.predict_proba(X_train_tf)[:,1]
y_valid_preds = knn.predict_proba(X_valid_tf)[:,1]

print('KNN')
print('Training:')
knn_train_auc, knn_train_accuracy, knn_train_recall, \
    knn_train_precision, knn_train_specificity = print_report(y_train,y_train_preds, thresh)
print('Validation:')
knn_valid_auc, knn_valid_accuracy, knn_valid_recall, \
    knn_valid_precision, knn_valid_specificity = print_report(y_valid,y_valid_preds, thresh)

KNN
Training:
AUC:0.673
accuracy:0.623
recall:0.533
precision:0.650
specificity:0.685
 
Validation:
AUC:0.662
accuracy:0.626
recall:0.528
precision:0.606
specificity:0.677
 


In [68]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(random_state = 42)
lr.fit(X_train_tf, y_train)

LogisticRegression(random_state=42)

In [69]:
y_train_preds = lr.predict_proba(X_train_tf)[:,1]
y_valid_preds = lr.predict_proba(X_valid_tf)[:,1]

print('Logistic Regression')
print('Training:')
lr_train_auc, lr_train_accuracy, lr_train_recall, \
    lr_train_precision, lr_train_specificity = print_report(y_train,y_train_preds, thresh)
print('Validation:')
lr_valid_auc, lr_valid_accuracy, lr_valid_recall, \
    lr_valid_precision, lr_valid_specificity = print_report(y_valid,y_valid_preds, thresh)



Logistic Regression
Training:
AUC:0.650
accuracy:0.608
recall:0.487
precision:0.643
specificity:0.730
 
Validation:
AUC:0.653
accuracy:0.622
recall:0.493
precision:0.608
specificity:0.731
 


In [71]:
from sklearn.metrics import f1_score

In [73]:
df.to_csv("Hackathon.csv")